kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: docker
    commands:
      - docker build -t my-app .

  - name: test
    image: node
    commands:
      - npm install
      - npm test

  - name: deploy
    image: golang
    commands:
      - go build
      - scp my-app user@server:/path/to/deployment
